#===============================================================================
# Copyright 2023 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================


[tool.black]
line-length = 90
extend-ignore = 'E203'

[tool.isort]
profile = "black"
line_length = 90

[tool.numpydoc_validation]
checks = [
    "all",   # report on all checks, except the below
    "GL08",  # only analyze functions with docstrings
    "RT02",  # conform with scikit-learn excludes
    "GL01",  # see https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/tests/test_docstrings.py
    "GL02",
    "PR02",
    "EX01",
    "SA01",
    "ES01"
]
exclude = [  # don't report on objects that match any of these regex
    '\._[^\.]*$',  # disregard private methods and functions
]
