#===============================================================================
# Copyright contributors to the oneDAL project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================
steps:
  - script: |
      curl -Os https://cli.codecov.io/latest/linux/codecov
      chmod +x codecov
    displayName: "Install codecov cli"
  - script: |
      PR="$(System.PullRequest.PullRequestId)"
      SHA=$(git rev-parse HEAD)
      VARARGS="-C ${SHA} -n azp-${SHA}-$(PYTHON_VERSION)-$(SKLEARN_VERSION)"
      if [ -n "${PR}" ]; then VARARGS="${VARARGS}-${PR} -P ${PR}"; fi
      ./codecov -v upload-process -Z -t $(CODECOV_TOKEN) $VARARGS -F azp -s ./coverage
    displayName: "Upload to codecov"

      
